#!/usr/bin/env python3

def transcription(t: str) -> str:
    if len(t) > 1000:
        raise ValueError("The length of the string must be less than 1000.")

    u: str = ""
    '''for c in t:
        if c == 'T':
            c = 'U'
            u = u + c
        else:
            u = u + c'''

    u = t.replace('T', 'U')
    return u


if __name__ == "__main__":
    t = "TTTTTCCACTGCCCTAGCCGTCAAAAACAGAGCCGTCGGCCGCTTTACTAATCATAACGTGTATTTTTTAGATCGTCCGGAAGGCGTAGCCCGTGGCACGGCCGAGCGGTGCCTCACTATTACCGGGTTAAAGACGACTCGCGGTCTGTCAACCATTGTGCGCAGGTTGAGGAAACCTTTGTCGCAACTGATTTTGAAATCCAATGCTCACAGTCGTCACATTCCGACAAACCGTTAATGGATATGTCGCCGGCATCGCTCATTGCACCCCATATATTAGCCAGGATAGCCAATACAACTGTGACAGTCTATGATCACTATGTTGCTCTCCCACCGGGTTACCTGTATCTGGCACGGAAGGTAAAGAAAACTGGAGGATTGGCGCAACTCTCAGGTGCCCAAGGACAAATGACACTCAGACCACTACTGCCCGTAACGACCAAAGTCGATTGGCGTAATGTGTCGCTGCATCACAGGAACCCTTAGACATAAGTTTCTAGTTCAGCACAGAACTACCTGCTTCTCCGGACAAACCCCTAGGGCACCCCCCAGAAATATGTAGAGCATAGTAGAAAATGTCCGGATTCAAGCCCGGCGGTAGGTAACTAATAACGCGCCTCCCGCTAGTGGAGAAAGACGCACCCTTCCTGCGGTCATAGGTCAGTCATCCACGTCATCATTGTCTAGAAATCAAAGCGGCAGCAGCTAAGCAATCGTTTATGGCACGTCTCGAATGGCTGCTTCGATGTACCACCCGAGCCTGACAAAGCACTACGGCACACATCACCCTCGTGCAGCATAACGAAGCGACTAAGAGCGCCGGCGTATACGTGCCAATGGGACTGGCAGCTGTTTTGTCGAATACGCAGCCACGTCGAAATAAGTTTTTGTATTACTAACCCCTGC"
    try:
        u = transcription(t)
        print(u)
    except ValueError as e:
        print(f"Error: {e}")
