#!/usr/bin/env python3

def rev_complement(s: str) -> str:
    if len(s) > 1000:
        raise ValueError("The length of the string must be less than 1000")

    reverse: str = s[::-1]

    s_c: str = ""
    s_c: str = reverse.translate(str.maketrans({'A': 'T', 
                                                'T': 'A', 
                                                'C': 'G',
                                                'G': 'C'}))
    return s_c


if __name__ == "__main__":
    s: str = "TGTCTTGATAACCTCAGAACTCGTAGTAGGAATACCGTTCAGACGCATCCCTCACCTGCACTAACGGATCCGTGGAACGATACTTGAAGCCGGGCCTAAGGCGACTCAATTTGGAAGATGCGAATGGCTCCAGTGGGGGACAGTAAAGCAGGGTTTTGCGGAAAGACAATCGTCCGAGCCTAACGAGTGAGATTCAGCGCAATTCGGCTAATGGATAGCGCTATAGTCACTCACATCTCCTTCTATGCTTAAATGCCTGGGACAGGAGAGGGCAATGACTTTTTAGCGTACAGATCTGCAGGGCATCCGGCCTGAGGGACTTCCCAGGGTTCGTGCACGCAGATGCCCAGATTCAGCAGAACTTCGTAAAGCGGTACGTTACGCATTCGCCCTAATTCGGTCTTAATTGGGAAAAAGTTCTGTCAAGAACAGGGGCCCCTTACGCTATGCTTCTGGGGAACTCGAAGATGATTGCACATCATTGGCGATAATTCGAGCGGCCAGGTACACGCGATTGGGAGCATGGTATCGCTTAGCGTTTAGAGAAGTTATAATACTCACCCGGACACTGGTCATAGTCTTCGCAGCGAGTTAAAATGTGCGTAGGACAGGAAACACACCTTGACCTGGTCACGTGCAGGAATATGTGCATGTACGTCCTGACTCGGAAACTTTAGCCGTTCTCAGCTCACAGAGCGCCCCTCTAGATCAGGCCCTGACTGTGAGGTTGGATGAAGGTCATCGGGGATTATCAACAGAACACGAGCCTGTGGCCGAAAGTGCACGCGTGCCGGACAAAAACAATCTAATC"
    s_c: str = rev_complement(s)
    print(s_c)
