#!/usr/bin/env python3


def counting(s: str) -> None:
    if len(s) > 1000:
        raise ValueError("The length of the string must be less than 1000.")
    A = s.count('A')
    C = s.count('C')
    G = s.count('G')
    T = s.count('T')
    print(A, C, G, T)


if __name__ == "__main__":
    s = "TCACATAATTTTGCTGTCTTCGTTCCATTTCGGATGTGGGTCGCAACACTGTTAACGTAACTTGACTCCAAAGTGTAGACTCCTATCCAGAGTTTATAAGTACTATTCCCCCTTGAGGCAAAATCTGAACTGTCTGTGCACCGGTACTACGTGACTGTACGTAGTTTTGTGGGCTAGTCCAAGACTACGTTGTAGTGCATCTATATCGGCCTTCTCGTGGCATGTCCCGATTGAAAGCTATTAATTAGCTGGCGCCCTTAGGCTCTGATAAGTTTAACTGTGGAGATTCCACTCCGTCGCCTTGATAATGGGGGTTCCGTTTGGTGAGAGGTGGTAAGATACGATGTAGACGATTATCGACCAATGTATTGATAGATAGGGCTTTAGGATTGGAAATCATTGCCCCTTAATTGAACAAGATGAGGCGCGACCTCGAGGGGTCACGGTACAGGGTAACATGTGTGTTTTGGGCTGTCACCGATTTCCGATCTATCTGAATGTGGCGTCACGGCCCATTGATGGGTTTCAATGTCAACAGGCTCTTTGGAGGACACAAGGGAACCAGTACGAGCTATCCAGTAAATACTCGGGTATCGGTGTCTCAGCCGTAGGCCGCGTCTCGATGTGTATAGGTAGAATTTTTTTCATGAGTTGTCATCGTAGGTGGGCAAGTGCTAGCGACTGGTCCACACTCGAGTGTATGTGTGATCAAGTTGGACCCAAAAGACAGCGCTTACTGTATTGGCGCAAGGCATGATCTTGTGGGGTCCCGGAGCTTGCACGGCGGATGGAGCCCTAAGCATGTAGCATTCATGCACTACATCCATTGGTGTGTTCATAGAACGGCATGGCTGGGTTTTTGGTTTTCACTCCAAAGCACTAACTATCCCATCTATGGTTATTTCGACAAAACCCAACGATGA"
    try:
        counting(s)
    except ValueError as e:
        print(f"Error: {e}")
