#!/usr/bin/env python3


def motif(s: str, t: str) -> list[int]:
    if len(s) == 0 or len(t) == 0:
        raise ValueError("Empty string")

    if len(s) > 1000 and len(t) > 1000:
        raise ValueError("At most 1 kbp")

    if len(s) <= len(t):
        raise ValueError("t must no longer than s")

    index: list[int] = []
    index = [i + 1 for i in range(len(s)) if s.startswith(t, i)]
    return index


if __name__ == "__main__":
    s: str = "ATAAAGGCGCAAAGGCGAAAGGCGTGTAAAGGCGGAAAGGCGCCTAAAGGCGGACAGAAAGGCGAAAAGGCGGAAAGGCGGGTAAAAGGCGCCTAAAAGGCGCCAAAAGGCGGGAAGAAAGGCGGAAAGGCGCCCAGAAAAGGCGAAAGGCGAGTAAAGGCGTGCAAAGGCGAAAAGGCGGCAAAGGCGAAAAGGCGAAAGGCGCAAAGGCGTTGGAGATAAAGGCGAAAGGCGGAAAAGGCGTAAAGGCGAAAGGCGTAAGAAAGGCGAAAGGCGAGAAAGGCGACAAAAGGCGCCGAAAGGCGAAAGGCGGAAAGGCGGCTAAAGGCGAAAGGCGCATAGTTTCACCAAAGGCGAGAAAGGCGTAAAGGCGCAAAGGCGAAAGGCGTCTAAAGGCGAAAGGCGGGTACAAAGGCGTGGAAAGGCGCTAAGTGAAAAGGCGAAAAGGCGAAAAAGGCGGAAAGGCGTGAAAAGGCGAAAAGGCGAAAGGCGCCCAAACTAGACAAAGGCGTTAAAAGGCGCAAAGGCGGGACTAAAGGCGAAAGGCGTGTTAAAGGCGGCATTAAAGGCGAAAGGCGGAAAGGCGTTAAAGGCGCATAAAGGCGAGGCTACGTAAAGGCGAAAGGCGCGCTGAAAGGCGAAAAGGCGAAAGGCGTAAAAGGCGTAAAGGCGCAAAGGCGAAAGGCGATAAGAAAGGCGAAAAGGCGCAAAGGCGCTTAAAGGCGTCCTAAAGGCGATAAAGGCGTAAAGGCGGAAAGGCGGATCGTAAAGGCGTATACAAAGGCGTAAAGGCGCTACAAAGGCGTTAAAGGCGTCAAAGGCGCAAAAGGCGGTAAAGGCGAAAGGCGCAAAGGCGAAAGGCGGGAAAGGCGTATCCTGAAAGGCGAAAGGCGGAAAGGCGGCGCTTTCGGGCAGGTCAAAGGCGGTGAAAGGCGTGGAAAGGCGAAAAGGCGAAAGGCGATAAAGGCGGAAAGGCGCC"
    t: str = "AAAGGCGAA"
    try:
        index = motif(s, t)
        print(*index)
    except ValueError as e:
        print(f"Error: {e}")
