#!/usr/bin/env python3

def hamming(s: str, t: str) -> int:
    count: int = 0
    if len(s) != len(t):
        raise ValueError("s and t must be of the same length.")
    if len(s) > 1000 or len(t) > 1000:
        raise ValueError("at most 1 kpb")
    for i, j in zip(s, t):
        if i != j:
            count += 1
    return count


if __name__ == "__main__":
    s: str = "TTGTCGATGAGTATATCGCCGGCCAGAGTCCGGGCAACTCGATCGTTAAAGTAACCCTCGTAAGAGAAAATTGTTTTGCTCAGGAACGTCATGACTGATTTTCTAAAAGGTTACTTCCGAGCGTGTATAAAGACATTTGCAGTGTCCATTAGCGCACCAGACAATTCTGGGGACACGCTTGGGCTTCCCCTACTTAAACGGACCCGAGGTCTCACGGACGGTCGAAGATAAACGCGCGCGATATGTGGCCTCGGATTCGTTTAGAGCTAGCGGGCGTTTGAGCGCCTTATAGTGATGATTTGACGAGATAAGAAGGGGAAAGAATACGTAGGGAGCGGGTGCTAGGCCAAGTTGCCTGCAAGGGGATAGTCGCCGCCCGAGCGTTCCTGCCCTTTAGCGTCTGCTGTAAGGGCGCCTGCCAAGGCACAAGACAAGTTTCGATTCCGGCCAGATCACCTATTCATTCACGAAACGCACCGGTGGCTCCTCCCTGCGGGCCGAGTAGAATAGTGTAAACGGTTTACAAGACCGAGTGTTACTTTAGAGAGCACGCTACGTTGGGGTTTGGTGGGCAGGCCGAGTTGGTCCCACGATATTGTTTCCCTGGGTGTATTGTCTCTCATCACGTTCCGTCTAATGCCACAGCATGATGAACGGACAATGTGGATTCTACGCGCAATGAGGTCAGAGCACTACCCTTAGCGTCAGCGTCGAAGGACCAGATTGAATAGATGCGGGACTGTTGGCTTACAGTGGGAGTCAGTCGATGATATCGGGCACCTCGATTGAGCCGGCAGCTAGCAGTTATCCCTGGACGATTACGTCGTACTCGTGCGTGACACACAACGGTGCCTTCATATTTTAAGCCCACGTTTGCCGCATGAGGGAGGTTTAACTGTTTCCATGTTGCAGCGGAATTTCAAGTGGACATGTCGC"
    t: str = "TTAGCAAAGAAGATCTGAGCGGCTAAAGTTTCAGTGTAGTTATCATTGAAGGAAGGCTTTGGCTTGAAAGTGCGTCTGATATTGCAGCTCTAAAGTAAGAAACGGTGCGGTGGTTTAGTGAAATGCAAATAAGTTTTTGCACTGTACGATAGCGTTCCAGGCGGACTTTGGGCCATTCGACGCATTCTCCTGCGTCAGAGGGAGAGAGGGGCCCGTGACCCCACTTGTCATTCCCTCCAGTGACGTCCCCTCGGTATGGTGAGGGCCCGTCAGCCGAAATCTGCTCATAAAAAGATTACATTAGTCCGAATGAGTAATAAAGATTTCCTAAGGTGCCGCTCCTATCCCAAGTTGCCTCCAGGGAGCGAGCAGCGTCCGCCCCACCCCTGCACCGTAGAGCTTGCTTAAGGGAAGGCCGCAATGAAACAAATTCAGGCGCGCTCCCCGCTTTTGAATTTAATGGACCAGGAAACGCGTTGTAGCATCCCCACGCTGAGGCGGGTTCCCTGATACCAACGGGGGCCCAGACCAACTAGTGATATCGGGAGCGCGATATGCTCTCGGCTGGGAGGTTACCCGAGGTCGTCTGACACTACATTGATCCGGGGTCCATGGTAAGCCATCTCTCGACGTCTAAAGTCCGGTAGTAAACCTCATGTGATGGGGGAATAGGGCTCTAAGCCCACACAGCCACCCCTTTCGAGTCTGGAAGGTCGAACCCTAGTGACCAACTAACGGACCGTATCCTTGCAATTGCAGGGCCCCGAAAGCATCCGTGCCCGCGTTTTACCACAGTTCCAGAATGAAACTCAGGGCCTGATAGCAGACTAATAAGAGTACATCTATCAAAGTGCTCCTCGGTAGAACTAACGAAAGTCGCTCGTTGGATTCTGTAGTGTATTCCTATTGTAGCGTATTATCAAATAAAATGGTCCA"
    try:
        count = hamming(s, t)
        print(count)
    except ValueError as e:
        print(f"Error: {e}")